CREATE TABLE [Production].[Products]
(
	ProductID INT PRIMARY KEY IDENTITY(1 , 1),
	ProductName NVARCHAR(50) NOT NULL,
	BrandID INT NOT NULL,
	CategoryID INT NOT NULL,
	ModelYear INT NOT NULL,
	CONSTRAINT FK_Products_CategoryID FOREIGN KEY(CategoryID) REFERENCES Production.Categories(CategoryID)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_Products_BrandID FOREIGN KEY(BrandID) REFERENCES Production.Brands(BrandID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
)