/*SELECT 
	CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME
FROM
	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
WHERE
	TABLE_NAME = 'Categories'


DECLARE @sql NVARCHAR(MAX) = '';
DECLARE @tableName NVARCHAR(128) = 'Production.Brands'

SELECT @sql += 'ALTER TABLE ' +
QUOTENAME(@tableName) + ' DROP CONSTRAINT ' + QUOTENAME(CONSTRAINT_NAME) + '; '
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'Brands' AND TABLE_SCHEMA = 'Production'

IF @sql <> ''
BEGIN
	EXEC sp_executesql @sql;
END
ELSE
BEGIN
	PRINT 'No Constraints found'
END

--print @sql*/