CREATE TABLE [dbo].[Branch]
(
	BranchID INT IDENTITY(1,3) PRIMARY KEY,
	BranchName NVARCHAR(50) NOT NULL,
	ManagerID INT NOT NULL,
	CONSTRAINT FK_BranchID_ManagerID FOREIGN KEY(ManagerID) REFERENCES Manager(ManagerID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

	--ALTER TABLE Branch
	--ADD CONSTRAINT FK_BranchID_ManagerID 
	--FOREIGN KEY(ManagerID) 
	--REFERENCES Manager(ManagerID)
	--ON DELETE NO ACTION ON UPDATE NO ACTION;

