CREATE TABLE [dbo].[Client]
(
	ClientID INT IDENTITY(0001,2) PRIMARY KEY,
	ClientName NVARCHAR(100) NOT NULL,
	BranchID INT NOT NULL,
	CONSTRAINT FK_ClientID_BranchID FOREIGN KEY(BranchID) REFERENCES Branch(BranchID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

	--ALTER TABLE Client
	--ADD CONSTRAINT FK_ClientID_BranchID 
	--FOREIGN KEY(BranchID) 
	--REFERENCES Branch(BranchID)
	--ON DELETE NO ACTION ON UPDATE NO ACTION;
;