CREATE TABLE [dbo].[Employee]
(
	EmployeeID INT IDENTITY(0001,1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	BirthDate DATE NOT NULL,
	Sex NVARCHAR(10) NOT NULL,
	Salary INT NOT NULL,
	BranchID INT NOT NULL,
	CONSTRAINT FK_EmployeeID_BranchID FOREIGN KEY(BranchID) REFERENCES Branch(BranchID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

	--ALTER TABLE Employee
	--ADD CONSTRAINT FK_EmployeeID_BranchID 
	--FOREIGN KEY(BranchID) 
	--REFERENCES Branch(BranchID)
	--ON DELETE NO ACTION ON UPDATE NO ACTION;