CREATE TABLE Sales.Customers
(
	CustomerID INT PRIMARY KEY IDENTITY (1, 1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Phone NVARCHAR(15) NOT NULL UNIQUE,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	Street NVARCHAR(255) NOT NULL,
	City NVARCHAR(50) NOT NULL,
	[State] NVARCHAR(50) NOT NULL,
	ZipCode INT NOT NULL
);