CREATE TABLE [Sales].[Order_Items]
(
	ItemID INT NOT NULL IDENTITY(1, 1),
	OrderID INT NOT NULL,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL,
	ListPrice INT NOT NULL, 
	Discount INT NOT NULL
	PRIMARY KEY(ItemID, OrderID),
	CONSTRAINT FK_Order_Items_ProductID FOREIGN KEY(ProductID) REFERENCES Production.Products(ProductID)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_Order_Items_OrderID FOREIGN KEY(OrderID) REFERENCES Sales.Orders(OrderID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
)