CREATE TABLE Sales.Orders
(
	OrderID INT PRIMARY KEY IDENTITY(1 , 1),
	CustomerID INT NOT NULL,
	OrderStatus NVARCHAR(50) NOT NULL,
	OrderDate DATE NOT NULL,
	RequiredDate DATE NOT NULL,
	ShippedDate DATE NOT NULL,
	StoreID INT NOT NULL,
	StaffID INT NOT NULL
	CONSTRAINT FK_Orders_CustomerID FOREIGN KEY(CustomerID) REFERENCES Sales.Customers(CustomerID)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_Orders_StaffID FOREIGN KEY(StaffID) REFERENCES Sales.Staff(StaffID)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_Orders_StoreID FOREIGN KEY(StoreID) REFERENCES Sales.Stores(StoreID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
)