CREATE TABLE Sales.Staff
(
	StaffID INT PRIMARY KEY IDENTITY(1 , 1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL UNIQUE,
	Phone NVARCHAR(15)  NOT NULL UNIQUE,
	Active BIT DEFAULT 1 NOT NULL,
	StoreID INT NOT NULL,
	ManagerID INT NOT NULL
	CONSTRAINT FK_Staff_StoreID FOREIGN KEY(StoreID) REFERENCES Sales.Stores(StoreID)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_Staff_ManagerID FOREIGN KEY(ManagerID) REFERENCES Sales.Staff(StaffID)
	ON DELETE NO ACTION ON UPDATE NO ACTION
)
