CREATE TABLE Sales.Stores
(
	StoreID INT PRIMARY KEY IDENTITY(1 , 1),
	StoreName NVARCHAR(50) NOT NULL,
	Phone NVARCHAR(15) NOT NULL UNIQUE,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	Street NVARCHAR(255) NOT NULL,
	[State] NVARCHAR(50) NOT NULL,
	ZipCode INT NOT NULL
)
